# Generated by Django 3.0 on 2020-09-17 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_player_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='MSF_PID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='player',
            name='sheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='players', to='api.Sheet'),
        ),
    ]
