# Generated by Django 3.0 on 2020-09-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200917_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='QBStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('week', models.BigIntegerField(blank=True, null=True)),
                ('season', models.BigIntegerField(blank=True, null=True)),
                ('homeoraway', models.TextField(blank=True, db_column='HomeOrAway', null=True)),
                ('opponent', models.TextField(blank=True, db_column='Opponent', null=True)),
                ('passattempts', models.BigIntegerField(blank=True, db_column='passAttempts', null=True)),
                ('passcompletions', models.BigIntegerField(blank=True, db_column='passCompletions', null=True)),
                ('passpct', models.FloatField(blank=True, db_column='passPct', null=True)),
                ('passyards', models.BigIntegerField(blank=True, db_column='passYards', null=True)),
                ('passavg', models.FloatField(blank=True, db_column='passAvg', null=True)),
                ('passyardsperatt', models.FloatField(blank=True, db_column='passYardsPerAtt', null=True)),
                ('passtd', models.BigIntegerField(blank=True, db_column='passTD', null=True)),
                ('passtdpct', models.FloatField(blank=True, db_column='passTDPct', null=True)),
                ('passint', models.BigIntegerField(blank=True, db_column='passInt', null=True)),
                ('passintpct', models.FloatField(blank=True, db_column='passIntPct', null=True)),
                ('passlng', models.BigIntegerField(blank=True, db_column='passLng', null=True)),
                ('pass20plus', models.BigIntegerField(blank=True, db_column='pass20Plus', null=True)),
                ('pass40plus', models.BigIntegerField(blank=True, db_column='pass40Plus', null=True)),
                ('passsacks', models.BigIntegerField(blank=True, db_column='passSacks', null=True)),
                ('passsacky', models.BigIntegerField(blank=True, db_column='passSackY', null=True)),
                ('qbrating', models.FloatField(blank=True, db_column='qbRating', null=True)),
            ],
        ),
    ]
