# Generated by Django 3.0 on 2020-09-19 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200919_1812'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QBStats',
            new_name='QBStat',
        ),
        migrations.DeleteModel(
            name='Mango',
        ),
    ]
