# Generated by Django 3.0 on 2020-09-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200919_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='city_team',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='dob',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='player',
            name='jersey_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='team_logo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='current_team',
            field=models.CharField(max_length=3),
        ),
    ]
