# Generated by Django 3.0 on 2020-09-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200920_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='qbstat',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
