# Generated by Django 3.0 on 2020-09-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_qbstat_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='has_stats',
            field=models.BooleanField(default=False),
        ),
    ]
